FROM golang:1.18-alpine

COPY . /app

WORKDIR /app

RUN apk add --no-cache git make build-base libpcap-dev

RUN mkdir -p /go/pkg/mod && \
    busybox unzip /app/v1.13.6.zip -d /go/pkg/mod

RUN go build ./cmd/assembler
